window.WAR_ROOM = {
  scrapedAt: "2026-08-31T18:01:39+02:00",
  scrapedLabel: "31 Aug 2026, 18:01 CEST · evening FINN pass",
  stats: {
    eiganesHouses: 17,
    valandHouses: 4,
    fitCount: 3,
    yoy: "11.1%",
    sqm: "~58k"
  },
  houses: [
    {
      id: "edvard-griegs",
      name: "Edvard Griegs vei 33",
      area: "Stokka",
      type: "Enebolig · rebuilt 2016 · 1960",
      ask: 14.5, total: 14.86, sqm: 187, plot: 689, beds: 3, year: 1960,
      status: "live", verdict: "watch",
      viewing: "Mon 7 Sep 16:00–17:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475184173",
      flags: ["baths", "garden", "garage", "gym", "newer"],
      scores: { family: 72, garden: 91, area: 92, risk: 76, forus: 82 },
      take: "New today: a handsome 2016 rebuild on a rare 689 m² blindvei plot, with 3 baths, carport and a 40 m² main suite. The basement soverom/kjellerstue is the only obvious second zone or gym path, and FINN still counts just 3 bedrooms. At 14.5m for 187 m², the garden is doing expensive work. Good layout recon; not a clean must-have fit."
    },
    {
      id: "rosestien",
      name: "Rosestien 1",
      area: "Stokka",
      type: "Enebolig · sokkel · 1999",
      ask: 12.5, total: 12.81, sqm: 292, plot: 582, beds: 7, year: 1999,
      status: "live", verdict: "strong",
      viewing: "Mon 31 Aug 16:30–17:30",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=474154858",
      flags: ["beds", "baths", "zones", "garden", "rental", "garage"],
      scores: { family: 90, garden: 80, area: 92, risk: 68, forus: 82 },
      take: "Still Ukens bolig and still the cleanest live Syrinveien rhyme near the reference price. Same 12.5m / 12.81 total, 292 m² BRA-i, 582 m² owned plot, 7 beds / 3 baths / 3 stuer, approved sokkel. Viewing Monday. Gym still eats the rental or a stue. Recon, not a bid."
    },
    {
      id: "adjunkt-hauglands",
      name: "Adjunkt Hauglands gate 28",
      area: "Stokka",
      type: "Enebolig · kjellerleilighet · 1984",
      ask: 13.5, total: 13.84, sqm: 307, plot: 498, beds: 4, year: 1984,
      status: "live", verdict: "strong",
      viewing: "Mon 7 Sep 17:00–18:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=474866838",
      flags: ["beds", "baths", "zones", "garden", "rental", "garage", "gym"],
      scores: { family: 94, garden: 84, area: 92, risk: 66, forus: 82 },
      take: "New today and a real brief-fit: 307 m² BRA-i, 498 m² owned plot, 4 bedrooms, several stuer, four wet rooms and an approved basement apartment. The blindvei garden is properly kid-shaped; the volume leaves a gym path without deleting family life. At 13.5m it is above reference and four wet rooms in a 1984 house are not decorative details. Strong recon, not a buy signal."
    },
    {
      id: "hoigard",
      name: "Lektor Einar Høigårds gate 1",
      area: "Eiganes vest / Lassa",
      type: "Enebolig",
      ask: 11.99, total: 12.29, sqm: 318, plot: 487, beds: 3, year: 1978,
      status: "live", verdict: "strong",
      viewing: "By appointment",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=462844743",
      flags: ["zones", "gym", "garden", "garage"],
      scores: { family: 80, garden: 72, area: 90, risk: 70, forus: 82 },
      take: "Unchanged volume play. 318 m² BRA-i / 338 m², 487 m² owned plot, terraces, double garage, extra kitchen downstairs. Official count is still 3 bedrooms / 4 rooms, so the fourth bed is paperwork. Same 11.99m. More gym-shaped than Rosestien, worse bedroom docs. Keep both."
    },
    {
      id: "ovrebo",
      name: "Øvrebøveien 3",
      area: "Våland",
      type: "Enebolig · 1972 · 1. etg 2018",
      ask: 9.25, total: 9.48, sqm: 242, plot: 558, beds: 3, year: 1972,
      status: "live", verdict: "watch",
      viewing: "Mon 31 Aug 17:00–18:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=474436092",
      flags: ["garden", "garage", "zones", "gym"],
      scores: { family: 70, garden: 78, area: 84, risk: 56, forus: 80 },
      take: "Yesterday’s useful arrival. 9.25m / 9.48 total, 242 m² BRA-i, 558 m² owned plot, garage + EV, greenhouse. Official 3 beds + office + 97 m² basement with hobby/verksted/kjellerstue — gym lives downstairs. Two baths plus two WCs. Price is the interesting part; bedroom count is still a paperwork fight. Viewing Monday 17–18. Watch, don’t sprint."
    },
    {
      id: "byfoged-finnes",
      name: "Byfoged Finnes gate 16",
      area: "Våland",
      type: "Tomannsbolig · eierseksjon · 1955",
      ask: 5.85, total: 6.0, sqm: 193, plot: 708, beds: 4, year: 1955,
      status: "live", verdict: "trap",
      viewing: "Thu 3 Sep 17:00–18:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=474643856",
      flags: ["beds", "baths", "zones", "garden", "gym", "garage"],
      scores: { family: 74, garden: 52, area: 84, risk: 24, forus: 84 },
      take: "New today and seductively cheap: 193 m² BRA-i, 4 approved bedrooms upstairs, 2 baths, garage and an 82 m² basement that can swallow a gym and second zone. Then the paperwork arrives. The 708 m² garden belongs to the two-section sameie, most of the basement conversion is unapproved, and the report flags elevated moisture, old drainage and wet-room risk. Useful floor-plan recon; a 5.85m trap until the basement and garden rights survive daylight."
    },
    {
      id: "bokfink",
      name: "Bokfinkveien 26",
      area: "Sandal",
      type: "Enebolig · 1954",
      ask: 9.5, total: 9.74, sqm: 160, plot: 1073, beds: 3, year: 1954,
      status: "sold", verdict: "sold",
      viewing: "Sold 27 Aug 2026 (FINN badge; ask 9.5m)",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=473900649",
      flags: ["garden", "garage", "zones"],
      scores: { family: 56, garden: 94, area: 76, risk: 34, forus: 80 },
      take: "Sold today at a 9.5m ask. Useful land comp: 1 073 m² owned plot at the end of a Sandal blindvei, Stokkavatnet next door, but only 160 m² BRA-i, 3 beds and a 1954 renovation invoice. The plot moved fast; the house still did not fit the brief."
    },
    {
      id: "vestbo",
      name: "Vestbøtunet 41A / 41B",
      area: "Stokka",
      type: "Enebolig · hybel/sokkel · two units",
      ask: 10.5, total: 10.76, sqm: 190, plot: 540, beds: 4, year: 1985,
      status: "live", verdict: "watch",
      viewing: "Tue 8 Sep 16:00–16:45",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=472851006",
      flags: ["beds", "garden", "zones", "rental"],
      scores: { family: 74, garden: 76, area: 91, risk: 62, forus: 82 },
      take: "Same 10.5m, now with a fresh 8 September viewing. 540 m² owned plot, 190 m² BRA-i, 4 beds, two boenheter plus rammetillatelse for extension/new garage. Could become a compound; today it is still a project wearing a nice jacket. Grade the floorplan, not the lake-view spell."
    },
    {
      id: "hornklove",
      name: "Torbjørn Hornkloves gate 37",
      area: "Våland",
      type: "Enebolig · 1915",
      ask: 11.99, total: 12.29, sqm: 261, plot: 396, beds: 3, year: 1915,
      status: "sold", verdict: "sold",
      viewing: "Sold 26 Aug 2026 (FINN badge; ask 11.99m)",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=473171110",
      flags: ["zones", "baths", "gym"],
      scores: { family: 69, garden: 58, area: 84, risk: 42, forus: 80 },
      take: "Sold today at a 11.99m ask. Useful Våland comp: 261 m² over four floors, 396 m² corner plot, two baths plus guest WC, loftstue and kjellerstue — but only three approved bedrooms. The 1915 / energy-F maintenance invoice did not stop it moving."
    },
    {
      id: "madlavei-6c",
      name: "Gamle Madlaveien 6C",
      area: "Eiganes",
      type: "Enebolig · new byvilla 2026",
      ask: 14.85, total: 14.92, sqm: 196, plot: null, beds: 3, year: 2026,
      status: "live", verdict: "dream",
      viewing: "By appointment / signup only",
      url: "https://www.finn.no/realestate/projectsingle/ad.html?finnkode=423023110",
      flags: ["zones", "newer", "premium"],
      scores: { family: 68, garden: 42, area: 90, risk: 80, forus: 84 },
      take: "Still the Eiganesveien 168 byvilla (project parent is also back on the search). 196 m², 3 (maybe 4) beds, ungdomsavdeling in the basement, handover Q3/Q4 2026. Garden is shared green, not a private kid-chaos plot. 14.85m is still boutique-hotel money. Dream/price ceiling, not a 2027 target."
    },
    {
      id: "madlavei-10",
      name: "Gamle Madlavei 10",
      area: "Eiganes",
      type: "Enebolig · new Swiss villa 2026",
      ask: 25.0, total: 25.63, sqm: 211, plot: 930, beds: 4, year: 2026,
      status: "live", verdict: "dream",
      viewing: "By appointment / signup only",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=454755791",
      flags: ["beds", "garden", "garage", "premium"],
      scores: { family: 76, garden: 94, area: 90, risk: 74, forus: 84 },
      take: "Rebuilt Swiss villa, 211 m², 4 beds, garage tag and a genuine 930 m² Eiganes plot. Garden math is unicorn. 25m for 211 m² is another religion. Keep as a plot/area ceiling, not a 2027 target."
    },
    {
      id: "eiganesveien-89",
      name: "Eiganesveien 89",
      area: "Eiganes",
      type: "Enebolig · jugend 1910",
      ask: 40.0, total: 41.02, sqm: 384, plot: 1049, beds: 5, year: 1910,
      status: "live", verdict: "dream",
      viewing: "By appointment",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=408193838",
      flags: ["beds", "garden", "garage", "premium"],
      scores: { family: 78, garden: 96, area: 92, risk: 28, forus: 84 },
      take: "Still listed: 384 m² Erga jugend, 1 049 m² owned plot, five stuer, spa/vinrom basement, energy G. Functionally a palace. 40m is another zip code. Keep as the absurd Eiganes cap, then look away."
    },
    {
      id: "steingata",
      name: "Steingata 41",
      area: "Eiganes",
      type: "Hel tomannsbolig",
      ask: 9.75, total: 10.0, sqm: 166, plot: 438, beds: 4, year: 1914,
      status: "live", verdict: "watch",
      viewing: "By appointment",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=465832042",
      flags: ["beds", "rental", "garage"],
      scores: { family: 64, garden: 48, area: 88, risk: 66, forus: 84 },
      take: "Still live. Whole two-family house with garage/parking, 2025 roof and 17k/month rental income. 166 m² is tight for compound mode, and a gym probably cannibalises the rental. Useful Eiganes foothold, weak family HQ."
    },
    {
      id: "bretland-28",
      name: "Bretlandsgata 28",
      area: "Eiganes",
      type: "Tomannsbolig · townhouse",
      ask: 15.9, total: 16.3, sqm: 179, plot: null, beds: 3, year: null,
      status: "live", verdict: "dream",
      viewing: "By appointment · Tue 25 viewing held",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=471177161",
      flags: ["baths", "zones", "premium"],
      scores: { family: 60, garden: 38, area: 92, risk: 78, forus: 84 },
      take: "Premium Eiganes townhouse: 3 beds, 3 baths, 4 stuer. Tuesday’s viewing is done; now by appointment. Lovely object, bad compound math. 15.9m for 179 m² is consulting-hour money. Dream/price ceiling, not a target."
    },
    {
      id: "bretland-30",
      name: "Bretlandsgata 30",
      area: "Eiganes",
      type: "Tomannsbolig · townhouse",
      ask: 15.9, total: 16.3, sqm: 175, plot: null, beds: 3, year: null,
      status: "live", verdict: "dream",
      viewing: "By appointment · Tue 25 viewing held",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=471179333",
      flags: ["premium", "newer"],
      scores: { family: 58, garden: 36, area: 92, risk: 80, forus: 84 },
      take: "Sibling to 28: new, polished, expensive, and too townhouse-shaped for the must-haves. Tuesday’s viewing is done; now by appointment. Compound money without compound outdoor space. Nice market reference, wrong target."
    },
    {
      id: "welhavens",
      name: "Welhavens gate 1A/B",
      area: "Eiganes",
      type: "Enebolig · approved apartment",
      ask: 22.5, total: 23.08, sqm: 272, plot: null, beds: 6, year: 2011,
      status: "live", verdict: "dream",
      viewing: "By appointment",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=448368685",
      flags: ["beds", "rental", "premium"],
      scores: { family: 82, garden: 52, area: 90, risk: 76, forus: 84 },
      take: "Eiganes, 2011, 272 m², 6 bedrooms and approved apartment. Functionally interesting, financially another solar system. 22.5m is a luxury comp, not a 2027 target."
    },
    {
      id: "misjonsveien",
      name: "Misjonsveien 52",
      area: "Kampen",
      type: "Del av tomannsbolig",
      ask: 4.49, total: 4.60, sqm: 87, plot: 222, beds: 2, year: 1912,
      status: "sold", verdict: "sold",
      viewing: "Sold 28 Aug 2026 (FINN badge; ask 4.49m)",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=471877789",
      flags: ["cheap"],
      scores: { family: 28, garden: 16, area: 62, risk: 68, forus: 78 },
      take: "Sold today at a 4.49m ask. Half a two-family house, 87 m² and 2 bedrooms: useful only as proof that cheap Kampen stock still moves. Fine student/BI object, zero compound."
    },
    {
      id: "drgraesli",
      name: "Dr. Græslis vei 13C",
      area: "Vålandskråningen",
      type: "Rekkehus",
      ask: 5.49, total: 5.63, sqm: 133, plot: 78, beds: 2, year: 1952,
      status: "live", verdict: "wrong",
      viewing: "Tue 1 Sep 16:30–17:30",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=473172605",
      flags: ["cheap"],
      scores: { family: 38, garden: 24, area: 76, risk: 70, forus: 80 },
      take: "Still the wrong little bastard, now with a Tuesday viewing. 133 m² rekkehus, 2 bedrooms, no compound garden and no rack+treadmill path without evicting normal life. Fine for someone else."
    },
    {
      id: "muse",
      name: "Muségata 55",
      area: "Våland",
      type: "Enebolig · 1911 sveitserjugend",
      ask: 10.29, total: 10.55, sqm: 173, plot: 257, beds: 3, year: 1911,
      status: "live", verdict: "wrong",
      viewing: "By appointment",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=463370141",
      flags: ["garden", "heritage"],
      scores: { family: 48, garden: 55, area: 84, risk: 40, forus: 78 },
      take: "Still listed. Prize-winning heritage villa, garden, garage, charm by the bucket. Also 173 m², three bedrooms and conservation constraints. Beautiful problem, wrong operating base."
    },
    {
      id: "furras",
      name: "Furras gate 15",
      area: "Våland",
      type: "Enebolig",
      ask: 6.95, total: 7.12, sqm: 201, plot: 161, beds: 5, year: 1910,
      status: "sold", verdict: "sold",
      viewing: "Sold 21 Aug 2026 (still badged Solgt on FINN)",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=472396798",
      flags: ["beds", "zones"],
      scores: { family: 58, garden: 28, area: 82, risk: 32, forus: 80 },
      take: "Still sold. Five bedrooms and a 1910 soul for 6.95m sounded clever until the 161 m² plot walked in. Keep a few weeks as the Våland-without-garden transact: rooms yes, kid chaos no."
    },
    {
      id: "jens-tvedts",
      name: "Jens Tvedts gate 4",
      area: "Kampen",
      type: "Tomannsbolig",
      ask: 4.99, total: 5.12, sqm: 116, plot: 374, beds: 4, year: 1935,
      status: "sold", verdict: "sold",
      viewing: "Sold 21 Aug 2026 (still badged Solgt)",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=468697314",
      flags: ["cheap", "beds"],
      scores: { family: 42, garden: 30, area: 64, risk: 66, forus: 78 },
      take: "Still sold. Kampen, 116 m² of a horizontal two-family. Four bedrooms at ~5m was cute market noise, not a compound. Drop once it stops teaching that the cheap Kampen slice actually moves."
    },
    {
      id: "spurve",
      name: "Spurvekroken 6",
      area: "Sandal",
      type: "Enebolig",
      ask: 8.5, total: 8.71, sqm: 240, plot: 330, beds: 3, year: 1983,
      status: "sold", verdict: "sold",
      viewing: "Sold 18 Aug 2026 (FINN badge timestamp)",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=469178413",
      flags: ["zones", "gym", "garage"],
      scores: { family: 70, garden: 62, area: 74, risk: 58, forus: 80 },
      take: "Still marked sold. Cheap Sandal comp: 240 m², 330 m² plot, garage, two kitchens/zones and a 1983 soul near Stokkavannet. Officially 3 bedrooms. This is what ~8.5m just bought when someone accepted the approval risk."
    },
    {
      id: "rogaland",
      name: "Rogalandsgata 19",
      area: "Våland",
      type: "Enebolig · 1917",
      ask: 15.0, total: 15.38, sqm: 347, plot: 902, beds: 6, year: 1917,
      status: "sold", verdict: "sold",
      viewing: "Sold / gone from the live Våland search",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=470177249",
      flags: ["beds", "garden", "zones", "gym", "rental", "garage"],
      scores: { family: 94, garden: 96, area: 86, risk: 62, forus: 80 },
      take: "Off the live search. Dream-comp: 347 m² BRA-i, 902 m² owned plot, 6 beds, double garage, basement rental. Teaches what 15m Våland unicorns look like when they vanish."
    },
    {
      id: "stokkavei",
      name: "Øvre Stokkavei 82A",
      area: "Stokka",
      type: "Enebolig",
      ask: 10.5, total: 10.76, sqm: 163, plot: 463, beds: 4, year: 1971,
      status: "sold", verdict: "sold",
      viewing: "Sold",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=472024319",
      flags: ["beds", "gym", "rental"],
      scores: { family: 76, garden: 55, area: 88, risk: 78, forus: 82 },
      take: "Still sold. 163 m² BRA-i on a 463 m² plot, built 1971, upgraded 2023–24, four bedrooms and hybel around 11k/month. This is what ~10.5m recently bought on Stokka after someone else did the wet-room suffering."
    },
    {
      id: "syrin",
      name: "Syrinveien 27 · benchmark",
      area: "Stokka",
      type: "Enebolig · ghost",
      ask: 12.5, total: 12.5, sqm: 300, plot: 700, beds: 3, year: 1978,
      status: "sold", verdict: "sold",
      viewing: "Sold June 2026 · tinglyst 8 Jun · public range 10–15m",
      url: "https://www.hjemla.no/norge/stavanger/4022-stavanger/syrinveien-27",
      flags: ["garden", "zones", "gym"],
      scores: { family: 88, garden: 90, area: 92, risk: 60, forus: 80 },
      take: "Permanent sold benchmark. Big Stokka house, big plot, enough internal weirdness to make the plan matter more than the bedroom count. Rosestien is the first live listing that rhymes with this street — still walk if the floorplan does not beat the feeling."
    }
  ]
};
