// Curated FINN.no family-house shortlist.
// Updated from live listing pages and broad Greater Stavanger search on 2026-09-11.
// Search coverage was broad but partial; stats are curated-card counts, not complete FINN inventory.

window.WAR_ROOM = {
  scrapedAt: "2026-09-11T18:05:15+02:00",
  scrapedLabel: "11 Sep 2026, 18:05 CEST",
  source: "FINN.no live ads plus broker pages",
  methodology: "Broad manual reconnaissance across Stavanger, Sola, Randaberg and northern Sandnes/Hommersåk. House types only. Listing facts were checked on live ad pages; commute, gym fit and verdicts are analyst inference. FINN's municipality search was accessible for Stavanger but partial or blocked elsewhere, so inventory totals are curated-card counts rather than complete market counts.",
  stats: {
    totalHouses: 34,
    stavangerHouses: 16,
    eiganesHouses: 3,
    valandHouses: 0,
    fitCount: 10,
    strongestScore: 79
  },
  houses: [
    {
      id: "postveien-10c",
      name: "Postveien 10C",
      area: "Madla, Stavanger",
      type: "Enebolig",
      ask: 13.2,
      total: 13.531,
      sqm: 260,
      plot: 650,
      beds: 5,
      year: 2015,
      status: "live",
      viewing: "21 Sep · 16:30–17:30",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=476119506",
      image: "",
      verdict: "dream",
      flags: ["family", "baths", "garden", "zones", "gym", "forus", "low-maintenance"],
      scores: { family: 98, garden: 78, area: 78, risk: 85, forus: 82 },
      score: 79,
      facts: [
        "FINN and the broker verify a 2015 detached house with 5 bedrooms, 260 m² BRA-i, 650 m² owned plot and 13.53m total",
        "The ad explicitly verifies 2 living rooms, 2 tiled bathrooms plus guest WC, laundry, south/west garden and an integrated garage",
        "The integrated garage is the plausible rack-and-treadmill solution without deleting a bedroom or second living room, subject to measurement (inference)",
        "Madla-to-Forus is roughly 12–22 minutes in ordinary traffic; Madlaveien/E39 queues can add friction (inference)"
      ],
      risks: [
        "At 13.53m total with no advertised rental unit, this is 1.03m above the owner-only reconnaissance ceiling",
        "Confirm the garage's clear floor area and that the photographed outdoor space includes level private child lawn",
        "A 2015 shell lowers near-term risk but does not replace permits, wet-room and condition diligence"
      ],
      take: "New dream/price benchmark: a genuinely complete modern family plan—five bedrooms, two stuer, two baths, sunny garden and plausible garage gym—in Madla. The house fits; the 13.53m owner-only total does not. Keep it as evidence of what the premium buys, not as permission for the budget to develop opinions."
    },
    {
      id: "mergelbakken-32",
      name: "Mergelbakken 32",
      area: "Sandved, Sandnes",
      type: "Enebolig",
      ask: 8.9,
      total: 9.141,
      sqm: 298,
      plot: 979,
      beds: 5,
      year: 1987,
      status: "live",
      viewing: "23 Sep · 17:00–18:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475887345",
      image: "https://images.finncdn.no/dynamic/1280w/2026/9/vertical-2/10/5/475/887/345_cbe1920e-3a25-4544-a787-c66b0fd27a0c.jpg",
      verdict: "strong",
      flags: ["family", "baths", "garden", "zones", "gym", "value", "forus"],
      scores: { family: 96, garden: 95, area: 62, risk: 58, forus: 92 },
      score: 77,
      facts: [
        "FINN and the broker verify 5 bedrooms, 298 m² BRA-i, 979 m² owned plot, 1987 build and 9.14m total",
        "The main floors provide a large living room, loft living room and two bathrooms; the basement apartment adds living/kitchen, bedroom and a third bathroom",
        "The basement is currently let for NOK 9,500/month, but neither FINN nor the accessible broker page verifies municipal approval; no rental flag or allowance is assigned",
        "Several basement stores/hobby rooms make a dedicated gym physically credible without deleting an owner bedroom or loft living room (inference)",
        "Sandved-to-Forus is roughly 8–15 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "Treat the current NOK 9,500/month tenancy as unapproved until municipal drawings and lawful unit status are produced; vacancy, maintenance, tax and tenant wear still apply",
        "Confirm that four legal owner bedrooms remain while the basement is occupied and that all advertised rooms match approved use",
        "The 1987 technical file requires drainage, wet-room, roof, electrical and alteration diligence"
      ],
      take: "New strongest value/volume candidate: 298 m², five bedrooms, two owner living zones, three bathroom spaces, near-1,000 m² plot and hobby-room gym potential at 9.14m total, close to Forus. The basement earns a verified advertised 9.5k/month, but legality is not verified, so the rental allowance remains exactly zero—the municipality has not been replaced by a tenant."
    },
    {
      id: "sorstrandveien-44",
      name: "Sørstrandveien 44",
      area: "Vassøy, Stavanger",
      type: "Enebolig",
      ask: 8.49,
      total: 8.703,
      sqm: 222,
      plot: 999,
      beds: 5,
      year: 2007,
      status: "live",
      viewing: "20 Sep · 14:00–16:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=476058250",
      image: "https://images.finncdn.no/dynamic/default/2026/9/vertical-2/10/0/476/058/250_fa2e3f41-1476-4e29-ab53-f2ac3cfec6d3.png",
      verdict: "watch",
      flags: ["family", "baths", "garden", "zones", "gym", "value"],
      scores: { family: 96, garden: 96, area: 58, risk: 55, forus: 42 },
      score: 74,
      facts: [
        "FINN verifies 5 bedrooms, 3 living rooms, 3 bathrooms, 222 m² BRA-i, 999 m² owned plot, 2007 build and 8.70m total",
        "The ad verifies a screened garden with fruit trees and greenhouse, several terraces, conservatory and garage",
        "Garage, conservatory and three living zones make a dedicated gym credible without deleting a bedroom or the core family plan (inference)",
        "The ad mentions a hybel but does not verify approval, separation or rent; no rental flag or allowance is assigned"
      ],
      risks: [
        "Vassøy requires a car ferry; a Forus trip is likely roughly 35–50 minutes door-to-door and timetable/queue dependent (inference)",
        "Verify the hybel and every lower-floor room against municipal approvals before assigning family or rental value",
        "Ferry dependence complicates school, activities and emergency logistics despite excellent house economics"
      ],
      take: "Location is not a gate, so this belongs in reconnaissance: five bedrooms, three stuer, three baths, real land and easy gym volume for 8.70m. The price is compensation for ferry dependence, not a clerical error. Treat the hybel as zero-income family flexibility until approvals and rent are documented."
    },
    {
      id: "vistafjords-27",
      name: "Vistafjords vei 27",
      area: "Hundvåg, Stavanger",
      type: "Enebolig",
      ask: 10.75,
      total: 11.02,
      sqm: 230,
      plot: 958,
      beds: 4,
      year: 1936,
      status: "live",
      viewing: "16 Sep · 16:00–17:30",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475438078",
      image: "https://images.finncdn.no/dynamic/1280w/2026/9/vertical-2/11/8/475/438/078_1464ea40-9caa-4dfb-ab63-fb553ba08c28.jpg",
      verdict: "watch",
      flags: ["family", "garden", "zones", "gym"],
      scores: { family: 90, garden: 95, area: 58, risk: 48, forus: 55 },
      score: 70,
      facts: [
        "FINN verifies 4 bedrooms, 230 m² BRA-i, 958 m² owned plot, 1936 build and 11.02m total",
        "The ad explicitly verifies several social zones, a large screened garden, 45 m² double garage with loft and an existing conservatory training room",
        "The basement is separated with its own entrance and contains hobby/workshop/guest rooms, but no rental unit is advertised or assumed",
        "Hundvåg-to-Forus is roughly 20–35 minutes in ordinary traffic and vulnerable to tunnel/E39 queues (inference)"
      ],
      risks: [
        "The ad verifies one large bathroom plus guest WC, not two full bathrooms; this fails the complete brief until the prospectus proves another bathroom or a credible legal conversion",
        "The 1936 shell, 1997–2001 renovation and basement uses require full condition, moisture and permit diligence",
        "Exactly four bedrooms leaves no spare legal-bedroom buffer"
      ],
      take: "A near-fit with unusually good land and a literal training room: four bedrooms, big social volume, 958 m² plot and double garage at 11.02m total. The defect is less photogenic but decisive—only one full bathroom is verified. Keep watching if a second-bath route survives the drawings and drainage department."
    },
    {
      id: "agatveien-15",
      name: "Agatveien 15",
      area: "Sandved, Sandnes",
      type: "Enebolig",
      ask: 10.99,
      total: 11.266,
      sqm: 188,
      plot: 439,
      beds: 4,
      year: 2026,
      status: "live",
      viewing: "13 Sep · 14:00–15:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=467085262",
      image: "https://images.finncdn.no/dynamic/1280w/2026/6/vertical-2/15/2/467/085/262_52205c16-c4ca-44ca-8291-a5495019a732.jpg",
      verdict: "strong",
      flags: ["family", "baths", "garden", "zones", "gym", "forus", "low-maintenance"],
      scores: { family: 100, garden: 65, area: 60, risk: 95, forus: 95 },
      score: 78,
      facts: [
        "FINN now verifies a completed 2026 freehold detached house with 4 bedrooms, 188 m² BRA-i and a 439 m² owned plot",
        "The current ad explicitly verifies 3 living rooms, 2 full bathrooms, separate laundry, garage and a garden",
        "A dedicated multipurpose cinema/training room makes rack plus treadmill plausible without deleting a bedroom or living zone (inference)",
        "Sandved-to-Forus is roughly 8–12 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "No rental unit is advertised; no rental allowance assumed",
        "The 439 m² plot is moderate, so verify level child-usable lawn after house, garage and terraces",
        "Exactly four bedrooms leaves no legal spare if a room fails approval or family function"
      ],
      take: "Best turnkey owner-only fit, but FINN's current facts are materially dearer and smaller-bedroomed than the previous card: four bedrooms, three living zones, two baths and a dedicated cinema/training room at 11.27m total. The 1.03m overnight correction belongs to the data, not necessarily the market; verify the 439 m² plot's actual child lawn."
    },
    {
      id: "gosenbakken-17",
      name: "Gosenbakken 17",
      area: "Madla/Gosen, Stavanger",
      type: "Enebolig",
      ask: 9.5,
      total: 9.739,
      sqm: 219,
      plot: 881,
      beds: 5,
      year: 1962,
      status: "live",
      viewing: "15 Sep · 16:30–17:30",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475811417",
      image: "https://images.finncdn.no/dynamic/1280w/2026/9/vertical-2/07/7/475/811/417_50beed4e-2f76-437a-b8f2-0d9a974a3528.jpg",
      verdict: "strong",
      flags: ["family", "baths", "garden", "zones", "gym", "value", "forus"],
      scores: { family: 98, garden: 95, area: 82, risk: 55, forus: 90 },
      score: 79,
      facts: [
        "FINN verifies 5 bedrooms, 219 m² BRA-i, 881 m² owned plot, 1962 build and 9.74m total",
        "The ad explicitly verifies 2 living rooms, 2 bathrooms, an 88 m² terrace, lawn with trampoline space and a 34 m² detached garage",
        "The detached garage or 14 m² external store makes a dedicated gym credible without deleting a bedroom or second living room, subject to measurement (inference)",
        "Madla/Gosen-to-Forus is roughly 10–18 minutes in ordinary traffic; Madlaveien/E39 queues can add friction (inference)"
      ],
      risks: [
        "The 1962 shell requires drainage, roof, wet-room, electrical, insulation and alteration diligence despite the polished presentation",
        "Verify that all five bedrooms and the lower-floor living room are approved for permanent use against municipal drawings",
        "No rental unit is advertised; no rental allowance assumed"
      ],
      take: "New functional leader at 9.74m total: five bedrooms, two proper living zones, two baths, a genuine 881 m² child plot and plausible detached-garage gym, with a practical Forus run. The compromise is a 1962 technical file wearing newer clothes; approvals and condition decide whether the value is real."
    },
    {
      id: "andrew-smiths-21",
      name: "Andrew Smiths gate 21",
      area: "Byhaugen, Stavanger",
      type: "Hel tomannsbolig",
      ask: 9.25,
      total: 9.483,
      sqm: 377,
      plot: 484,
      beds: 6,
      year: 1949,
      status: "live",
      viewing: "17 Sep · 16:30–17:30",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475907055",
      image: "https://images.finncdn.no/dynamic/1280w/2026/9/vertical-2/08/5/475/907/055_860b47c1-f3af-4759-86a8-2706f73ed055.jpg",
      verdict: "watch",
      flags: ["family", "baths", "garden", "zones", "gym", "rental", "value"],
      scores: { family: 95, garden: 70, area: 88, risk: 30, forus: 80 },
      score: 74,
      facts: [
        "FINN verifies a complete freehold duplex with 6 bedrooms, 377 m² BRA-i, 484 m² owned plot, 1949 build and 9.48m total",
        "The prospectus verifies three bathrooms, several living rooms, lawn, south-facing terrace and a 21 m² integrated garage",
        "The municipality has approved the property as a complete duplex with two dwellings that may be rented; advertised or achieved rent is not stated and needs verification",
        "The garage or very large internal volume makes rack plus treadmill credible, but the exact room must be measured without sacrificing parking or a legal family room (inference)",
        "Byhaugen-to-Forus is roughly 12–22 minutes in ordinary traffic; E39 queues can add friction (inference)"
      ],
      risks: [
        "Do not underwrite 15k/month until unit division, separation and a current lease or market evidence are checked; vacancy, maintenance, tax and tenant wear apply",
        "The prospectus says current basement and loft use diverges from approved 1948 drawings; bathroom, kitchen and living-room changes may be unapproved",
        "The 1949 shell has material technical risk, including old wet-room elements, possible chimney moisture, floor deviations and an electrical system needing extended inspection",
        "Verify which four bedrooms and two living zones remain in one coherent owner volume if the other dwelling is rented"
      ],
      take: "The new volume-and-rental watch: a legal two-dwelling duplex, six bedrooms, three baths, lawn and 377 m² at 9.48m total. Rent is unpriced, and the basement/loft contain unapproved use changes plus 1949-condition risk. Excellent reconnaissance; not permission to capitalize imaginary rent or ignore the municipal paperwork department."
    },
    {
      id: "rosehagen-42",
      name: "Rosehagen 42",
      area: "Stokka, Stavanger",
      type: "Enebolig/kjedehus",
      ask: 9.3,
      total: 9.534,
      sqm: 207,
      plot: 154,
      beds: 4,
      year: 2012,
      status: "live",
      viewing: "16 Sep · 16:30–17:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475974844",
      image: "https://images.finncdn.no/dynamic/1280w/2026/9/vertical-2/09/4/475/974/844_7d2660e4-30f0-4a75-9d40-b8c8fb6005a9.jpg",
      verdict: "watch",
      flags: ["family", "baths", "garden", "zones", "gym", "forus", "low-maintenance"],
      scores: { family: 90, garden: 45, area: 95, risk: 45, forus: 82 },
      score: 65,
      facts: [
        "FINN and the broker verify 4 bedrooms, 207 m² BRA-i, 3 living rooms, 3 bathrooms plus WC, 2012 build and 9.53m total",
        "The owned plot is only 154 m², but the broker verifies a private screened 33 m² ground terrace suitable for small children plus a 17 m² roof terrace",
        "The broker explicitly describes the basement living room as a combined youth/gaming/training room with adjacent sauna and shower",
        "Stokka-to-Forus is roughly 12–22 minutes in ordinary traffic; E39 peak queues can add friction (inference)"
      ],
      risks: [
        "The broker says the basement was not building-approved: its living room, bathroom and sauna remain approved only as an unfinished ancillary basement, so the gym/family value is conditional",
        "The top advertised bedroom is building-approved as a living room; confirm bedroom daylight, escape and fire requirements before counting it conservatively",
        "Outdoor space is private and usable but terrace-led rather than a real lawn garden",
        "Several wet rooms lack membrane documentation, and the electrical documentation is incomplete; no rental unit is advertised"
      ],
      take: "A rare sub-10m Stokka functional watch: four advertised bedrooms, three living zones, three baths and an existing training room. The price is attractive because the plot is a 154 m² terrace proposition and the basement is not approved for its current use. Very good daily logistics; not the garden benchmark, and the paperwork has eaten the gym before breakfast."
    },
    {
      id: "akselmarka-3",
      name: "Akselmarkå 3",
      area: "Håbafjell, Sandnes",
      type: "Enebolig",
      ask: 7.79,
      total: 7.986,
      sqm: 222,
      plot: 353,
      beds: 5,
      year: 1998,
      status: "live",
      viewing: "16 Sep · 18:15–19:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=476013772",
      image: "https://images.finncdn.no/dynamic/1280w/2026/9/vertical-2/10/2/476/013/772_6503e1b3-07c3-4f87-850a-6d49808e2d49.jpg",
      verdict: "watch",
      flags: ["baths", "garden", "zones", "gym", "rental", "value", "forus"],
      scores: { family: 72, garden: 52, area: 52, risk: 68, forus: 85 },
      score: 64,
      facts: [
        "FINN and DNB verify 5 bedrooms, 222 m² BRA-i, 353 m² owned plot, 1998 build and 7.99m total",
        "The ad explicitly verifies an approved two-bedroom basement apartment; advertised or achieved rent is not stated and needs verification",
        "The main dwelling has three bedrooms and several living areas; the property also has a garage, 81 m² of terraces and landscaped outdoor space",
        "The garage makes rack plus treadmill plausible subject to dimensions and retained parking (inference)",
        "Håbafjell-to-Forus is roughly 12–22 minutes in ordinary traffic; E39 congestion can add friction (inference)"
      ],
      risks: [
        "Keeping the approved apartment rented leaves only three owner bedrooms, below the family brief",
        "Do not underwrite 15k/month until unit separation, condition and a current lease or market evidence are checked; vacancy, maintenance, tax and tenant wear apply",
        "The 353 m² plot is compact and terrace-heavy, so verify level private lawn; confirm bathroom count and garage dimensions in the complete prospectus"
      ],
      take: "New low-price legal-rental watch at 7.99m total. The two-bedroom apartment is approved, but rent is unstated and the owner part has only three bedrooms while it is let. Useful economics reconnaissance; not a complete six-person-family solution unless the unit is reclaimed, which rather defeats the income argument."
    },
    {
      id: "hauagata-10",
      name: "Hauagata 10",
      area: "Trones, Sandnes",
      type: "Enebolig",
      ask: 12.9,
      total: 13.224,
      sqm: 323,
      plot: 702,
      beds: 6,
      year: 2017,
      status: "live",
      viewing: "20 Sep · 14:00–15:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475886648",
      image: "https://images.finncdn.no/dynamic/1280w/2026/9/vertical-2/08/8/475/886/648_09e8a0e4-05da-4610-9b3d-504483bdf7eb.jpg",
      verdict: "watch",
      flags: ["family", "baths", "garden", "zones", "gym", "rental", "forus", "low-maintenance"],
      rentMonthly: 10000,
      scores: { family: 80, garden: 78, area: 68, risk: 80, forus: 95 },
      score: 76,
      facts: [
        "FINN verifies a 2017 property sold as two sections with 6 bedrooms, 323 m² BRA-i, 702 m² owned plot and 13.22m total",
        "The main section contains 3 upstairs bedrooms plus an approved 2-bedroom basement bedsit currently let for NOK 10,000/month; the second 60 m² section has one bedroom",
        "Multiple living zones and a 39 m² garage make a dedicated rack-and-treadmill room physically credible (inference)",
        "Trones-to-Forus is roughly 8–15 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "The verified NOK 10k/month rent is below the 15k target; rent for the separate 60 m² section is not advertised and must not be invented",
        "Keeping the approved bedsit let leaves only three bedrooms in the main family volume; using the separately sectioned flat for family life is possible but operationally awkward and needs legal/physical review",
        "Vacancy, tenant wear, maintenance, tax/legal compliance and loss of family space reduce the headline rental value; verify lawn area within the landscaped plot"
      ],
      take: "New rental watch at 13.22m total: unusually flexible 2017 volume, two legal sections, an approved two-bedroom bedsit actually earning 10k/month, and a 39 m² garage. The income is real but below target, and the owner volume has only three conventional bedrooms while the bedsit is occupied—the arithmetic has declined to be impressed by the square metres."
    },
    {
      id: "friheim-52",
      name: "Friheim 52",
      area: "Hafrsfjord/Sunde, Stavanger",
      type: "Enebolig",
      ask: 7.59,
      total: 7.781,
      sqm: 185,
      plot: 711,
      beds: 5,
      year: 1987,
      status: "live",
      viewing: "15 Sep · 16:00–17:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475380820",
      image: "https://images.finncdn.no/dynamic/1280w/2026/9/vertical-2/03/0/475/380/820_9d87df17-2dbe-41ff-bdcd-8ea37c489d22.jpg",
      verdict: "strong",
      flags: ["family", "baths", "garden", "zones", "gym", "value"],
      scores: { family: 92, garden: 88, area: 65, risk: 65, forus: 70 },
      score: 74,
      facts: [
        "FINN verifies 5 bedrooms, 185 m² BRA-i, 711 m² owned plot and 1987 build",
        "The ad describes a loft living room plus several main-floor living zones, a screened lawn garden, terrace and double garage",
        "FINN's room/gallery material shows a first-floor guest bathroom and a second-floor bathroom",
        "The double garage makes rack plus treadmill credible without deleting a bedroom or living zone (inference)",
        "Friheim-to-Forus is roughly 18–30 minutes in ordinary traffic; Madlaveien/E39 queues can add friction (inference)"
      ],
      risks: [
        "Confirm both bathrooms' approved status and condition in the complete sales prospectus",
        "A garage gym must be measured and tested against retaining practical parking/storage",
        "No rental unit is advertised; no rental allowance assumed, and 1987 wet rooms, drainage and alterations need diligence"
      ],
      take: "Best fresh value fit: five bedrooms, two living levels, two bathroom spaces, a real 711 m² garden and plausible double-garage gym at 7.78m total. The west-side Forus run is workable rather than elegant; verify bathrooms, garage dimensions and the 1987 technical file before promoting it beyond reconnaissance."
    },
    {
      id: "skadbergbakken-22",
      name: "Skadbergbakken 22",
      area: "Skadberg, Sola",
      type: "Enebolig",
      ask: 9.49,
      total: 9.728,
      sqm: 215,
      plot: 547,
      beds: 5,
      year: 1993,
      status: "live",
      viewing: "15 Sep · 18:30–19:30",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475376181",
      image: "https://images.finncdn.no/dynamic/default/2026/9/vertical-2/02/1/475/376/181_c51cbec0-e179-45e6-a453-5f29a9448dce.jpg",
      verdict: "strong",
      flags: ["family", "baths", "garden", "zones", "gym"],
      scores: { family: 88, garden: 78, area: 70, risk: 58, forus: 92 },
      score: 71,
      facts: [
        "FINN verifies 5 bedrooms, 215 m² BRA-i, 547 m² owned plot and 1993 build; total 9.73m",
        "Main house: open living/kitchen plus WC on the entry floor, three bedrooms and a bathroom upstairs",
        "The basement is fitted as a separate apartment with living/kitchen, two bedrooms, bathroom and laundry; the ad calls it suitable for rental, guests or family, but does not say godkjent",
        "The ad states the garage has previously been used as a training/yoga room, with EV charging and two outdoor parking spaces",
        "Skadberg-to-Forus is roughly 8–15 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "No rental flag: a fitted basement apartment is not evidence of municipal approval, and rent needs verification",
        "Using the basement as income would leave the owner with three bedrooms and one living zone — below the family brief",
        "1993 fabric plus the 2011 kitchen extension needs permits, wet-room, drainage and alteration diligence"
      ],
      take: "New complete-paper fit at 9.73m: five bedrooms, two baths, a real garden and a garage already used as a gym. Treat the basement as family space until the municipality says otherwise; the brochure's enthusiasm for utleie is not a planning decision."
    },
    {
      id: "asperholen-169",
      name: "Asperholen 169",
      area: "Asperholen, Sandnes",
      type: "Enebolig",
      ask: 9.5,
      total: 9.739,
      sqm: 313,
      plot: 526,
      beds: 6,
      year: 1990,
      status: "live",
      viewing: "By appointment",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=465293643",
      image: "https://images.finncdn.no/dynamic/default/2026/5/vertical-2/29/3/465/293/643_60029efc-790d-48d1-9cdc-9676bc69a30d.jpg",
      verdict: "strong",
      flags: ["family", "baths", "garden", "zones", "gym", "rental"],
      scores: { family: 90, garden: 68, area: 52, risk: 72, forus: 72 },
      score: 74,
      facts: [
        "FINN verifies 6 bedrooms, 313 m² BRA-i, 526 m² owned plot, 1990 build and 9.74m total",
        "The ad explicitly states a godkjent utleiedel, three bathrooms and a double garage with an insulated loft",
        "Terraces total 134 m² TBA; the plot is 526 m², so child-usable lawn still needs a site check",
        "Advertised or achieved rent is not stated and must be verified",
        "Asperholen-to-Forus is roughly 12–22 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "Do not underwrite 15k/month until unit size, separation, demand and the approval documents are checked",
        "Vacancy, tenant wear, maintenance, tax treatment and the family-space sacrificed to the unit remain real costs",
        "Confirm how many of the six bedrooms remain if the approved unit is kept let"
      ],
      take: "New rental-and-volume candidate: 313 m², six bedrooms, three baths, approved unit and double garage at 9.74m total. The location is not the benchmark, but Forus is practical. Rent is unverified, so the +2m allowance is a hypothesis until a lease or market evidence exists."
    },
    {
      id: "blokkebaervegen-13",
      name: "Blokkebærvegen 13",
      area: "Hålandsmarka, Ræge",
      type: "Enebolig",
      ask: 10.9,
      total: 11.174,
      sqm: 323,
      plot: 513,
      beds: 4,
      year: 2008,
      status: "live",
      viewing: "15 Sep · 17:00–19:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=472799031",
      image: "https://images.finncdn.no/dynamic/default/2026/8/vertical-2/10/1/472/799/031_28f56d51-4ce7-4fa1-ae79-7c6f9e0abdf4.jpg",
      verdict: "strong",
      flags: ["family", "baths", "garden", "zones", "gym", "forus"],
      scores: { family: 98, garden: 70, area: 55, risk: 85, forus: 95 },
      score: 76,
      facts: [
        "FINN verifies 4 bedrooms, 323 m² BRA-i, 513 m² owned plot and 2008 build",
        "The ad explicitly verifies 3 living rooms, 2 bathrooms, a cinema room and double garage",
        "Landscaped lawn and several terraces provide private child-usable outdoor space",
        "The broker states about 15 minutes to Forus; peak-hour variability still needs a real commute test"
      ],
      risks: [
        "Exactly four bedrooms leaves no spare legal bedroom, although the cinema or one of three living zones can absorb a gym without breaking the family plan",
        "No rental unit is advertised; no rental allowance assumed",
        "Ræge is farther from central Stavanger and school walking distance should be checked against the family's actual catchment"
      ],
      take: "Still a complete brief match on paper—four bedrooms, three living zones, two baths, lawn, cinema and double garage—at 11.17m total. The location is not the benchmark, but the advertised 15-minute Forus run makes that a preference cost rather than a veto."
    },
    {
      id: "brauta-23",
      name: "Brauta 23",
      area: "Øvre Vaulen, Stavanger",
      type: "Enebolig",
      ask: 10.99,
      total: 11.266,
      sqm: 245,
      plot: 723,
      beds: 4,
      year: 1975,
      status: "live",
      viewing: "By appointment",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=473676094",
      image: "https://images.finncdn.no/dynamic/1280w/2026/8/vertical-2/18/4/473/676/094_274d6dc3-387c-4c8b-aebd-fc18587d2c72.jpg",
      verdict: "strong",
      flags: ["family", "baths", "garden", "gym", "forus"],
      scores: { family: 90, garden: 88, area: 82, risk: 60, forus: 100 },
      score: 76,
      facts: [
        "FINN verifies 4 bedrooms, 245 m² BRA-i, 723 m² owned plot and 1975 build",
        "The ad verifies 2 bathrooms, laundry, two storage rooms, garage and a landscaped private garden",
        "The 245 m² internal footprint makes a non-bedroom training zone plausible, but its exact location needs the plan and measurements (inference)",
        "Øvre Vaulen gives a practical Forus run of roughly 7–15 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "The ad describes living/dining/TV space together rather than proving two acoustically useful living zones; verify the floor plan",
        "Exactly four bedrooms leaves no legal spare if one room fails approval or function",
        "1975 construction requires drainage, wet-room, roof, electrical and alteration diligence; no rental unit is advertised"
      ],
      take: "The strongest land-and-location candidate still live: four bedrooms, two baths, 245 m², a TV zone and a real 723 m² garden at 11.27m total, close to Forus. Dedicated gym space remains inferred rather than advertised."
    },
    {
      id: "adjunkt-hauglands-28",
      name: "Adjunkt Hauglands gate 28",
      area: "Stokka, Stavanger",
      type: "Enebolig",
      ask: 13.5,
      total: 13.839,
      sqm: 307,
      plot: 498,
      beds: 4,
      year: 1984,
      status: "sold",
      viewing: "Sold 8 Sep · final price not visible",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=474866838",
      image: "https://images.finncdn.no/dynamic/default/2026/8/vertical-2/28/8/474/866/838_81eae50a-ddf2-44f3-b9fd-c70acbf183d2.jpg",
      verdict: "sold",
      flags: ["family", "baths", "garden", "zones", "gym", "rental"],
      scores: { family: 82, garden: 82, area: 93, risk: 62, forus: 85 },
      score: 77,
      facts: [
        "FINN verifies 4 bedrooms, 307 m² BRA-i, 498 m² owned plot, 1984 build and 13.84m total",
        "The ad explicitly states a godkjent kjellerleilighet, several living rooms, four wet rooms and a screened garden with lawn",
        "Advertised rent is not stated and must be verified",
        "Garage is advertised; a dedicated gym is therefore physically plausible (inference)",
        "Stokka-to-Forus is roughly 12–22 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "Asking 13.5m exceeds the 11m owner-only baseline; the +2m rental ceiling only applies if the approved unit actually yields about 15k/month",
        "Vacancy, tenant wear, maintenance, tax/legal compliance and loss of family space reduce headline income value",
        "Confirm how many of the four bedrooms remain in the owner volume if the basement is kept let"
      ],
      take: "Sold on 8 Sep. Retain briefly as a Stokka rental-and-volume comp at 13.84m advertised total; achieved price and rent remain unpublished. The +2m rental allowance still requires evidence near 15k/month, even after the market has completed its paperwork without us."
    },
    {
      id: "sandestubben-11",
      name: "Sandestubben 11",
      area: "Sande, Sola",
      type: "Enebolig",
      ask: 8.49,
      total: 8.698,
      sqm: 257,
      plot: 985,
      beds: 6,
      year: 1970,
      status: "sold",
      viewing: "Sold 11 Sep · final price not visible",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=474749842",
      image: "https://images.finncdn.no/dynamic/default/2026/9/vertical-2/01/2/474/749/842_a45367f5-87c5-4349-88d0-038071ff9f31.jpg",
      verdict: "sold",
      flags: ["family", "baths", "garden", "zones", "gym", "value", "forus"],
      scores: { family: 92, garden: 95, area: 65, risk: 55, forus: 85 },
      score: 75,
      facts: [
        "FINN verifies 6 bedrooms, 257 m² BRA-i, 985 m² owned plot and 1970 build",
        "The ad describes a screened landscaped garden, several outdoor zones and a double garage",
        "The furnished basement contains two bedrooms, a living room/kitchen and a bathroom; this supplies a second living zone but is not advertised as an approved rental unit",
        "Sande-to-Forus is roughly 12–22 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "No rental flag: verify basement approvals, escape routes and room legality before assigning either family or income value",
        "1970 construction requires drainage, wet-room, electrical, roof and alteration diligence",
        "A garage gym is credible, but confirm clear internal dimensions and whether vehicles can still be accommodated"
      ],
      take: "Sold on 11 Sep; achieved price is not visible. Retain briefly as the 8.70m advertised Sola comp for six bedrooms, two living levels, two baths, near-1,000 m² plot and double garage. The basement was never verified as a legal rental unit."
    },
    {
      id: "tvarabergkroken-22",
      name: "Tvarabergkroken 22",
      area: "Madla/Revheim, Stavanger",
      type: "Enebolig",
      ask: 9.65,
      total: 9.91,
      sqm: 211,
      plot: 387,
      beds: 5,
      year: 2007,
      status: "live",
      viewing: "14 Sep · 16:30–17:30",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475546552",
      image: "https://images.finncdn.no/dynamic/1280w/2026/9/vertical-2/04/2/475/546/552_9a053438-8458-4cce-9ab2-8e65f0248646.jpg",
      verdict: "strong",
      flags: ["family", "baths", "garden", "zones", "gym", "value"],
      scores: { family: 95, garden: 70, area: 75, risk: 70, forus: 80 },
      score: 74,
      facts: [
        "FINN verifies 5 bedrooms, 211 m² BRA-i, 387 m² owned plot and 2007 build",
        "The ad explicitly describes three living rooms, two bathrooms, garage, garden, terrace and hagestue",
        "Garage/bod volume makes rack plus treadmill credible without deleting a bedroom or living room, subject to measurement (inference)",
        "Madla/Revheim to Forus is roughly 15–25 minutes in ordinary traffic; Madlaveien and E39 queues can add friction (inference)"
      ],
      risks: [
        "The plot is compact, so verify the photographed lawn is private, level and genuinely useful once terraces and buildings are excluded",
        "The ad calls the second-floor office and bod unapproved; obtain the completion certificate and approved drawings for the entire plan",
        "No rental unit is advertised; no rental allowance assumed"
      ],
      take: "Still a complete-paper fit: five bedrooms, three living rooms, two baths, garden and plausible dedicated gym space at 9.91m total. The 387 m² plot is the compromise, and the expressly unapproved office/bod means the municipal file—not the styling—gets the last word."
    },
    {
      id: "vestbotunet-41",
      name: "Vestbøtunet 41A/B",
      area: "Stokka, Stavanger",
      type: "Enebolig",
      ask: 9.95,
      total: 10.2,
      sqm: 190,
      plot: 540,
      beds: 4,
      year: 1985,
      status: "live",
      viewing: "22 Sep · 16:00–17:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=472851006",
      image: "https://images.finncdn.no/dynamic/default/2026/8/vertical-2/18/6/472/851/006_4bf1cb8b-2beb-4876-b9ab-1ee264a334d6.jpg",
      verdict: "watch",
      flags: ["family", "baths", "garden", "zones", "rental"],
      scores: { family: 78, garden: 70, area: 92, risk: 58, forus: 82 },
      score: 72,
      facts: [
        "FINN verifies 4 bedrooms, 190 m² BRA-i, 540 m² owned plot, 1985 build and the reduced 10.20m total",
        "The ad states the house is registered as an enebolig with hybel/sokkelleilighet and two boenheter; the secondary unit was upgraded in 2022",
        "Advertised rent is not stated and must be verified",
        "A rammetillatelse exists for extension, facade changes, a new garage and an extra driveway — there is no current garage gym",
        "Stokka-to-Forus is roughly 12–22 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "The fourth bedroom sits in the secondary unit: keeping it let leaves three owner bedrooms, below the family brief",
        "No dedicated gym volume is established until the permitted garage is built and measured",
        "Vacancy, tenant wear, maintenance, tax/legal compliance and loss of family space apply if the unit is used for income"
      ],
      take: "Live Stokka after a verified 0.55m ask cut: now 10.20m total with two registered units and a lake view. Good preferred-belt reconnaissance. It is not a gym answer today, and rent remains unstated—do not spend the +2m until the lease and approvals are on the table."
    },
    {
      id: "bulegsbakken-22",
      name: "Bulegsbakken 22",
      area: "Grødem, Randaberg",
      type: "Enebolig",
      ask: 7.85,
      total: 8.067,
      sqm: 216,
      plot: 481,
      beds: 4,
      year: 1981,
      status: "live",
      viewing: "15 Sep · 16:00–17:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=465650180",
      image: "https://images.finncdn.no/dynamic/1280w/2026/9/vertical-2/02/0/465/650/180_346d41ca-6ed1-45dc-9c6d-ad32fd2dfb16.jpg",
      verdict: "watch",
      flags: ["family", "baths", "garden", "zones", "gym", "value"],
      scores: { family: 92, garden: 75, area: 55, risk: 55, forus: 55 },
      score: 68,
      facts: [
        "FINN verifies 4 bedrooms, 216 m² BRA-i, 481 m² owned plot and 1981 build",
        "The ad explicitly verifies 2 living rooms, 2 tiled bathrooms plus guest WC, a sunny zoned garden and 28 m² garage",
        "The lower floor was previously used partly as a rental section, but the ad does not verify present approval, separation or rent",
        "The garage/lower-floor volume makes a dedicated gym credible, subject to plans and measurement (inference)",
        "Grødem-to-Forus is roughly 25–35 minutes in ordinary traffic and vulnerable to E39 queues (inference)"
      ],
      risks: [
        "No rental flag or allowance: previous rental use is not evidence of a legal rentable unit, and rent needs verification",
        "Vacancy, tenant wear, maintenance, tax/legal compliance and loss of family space apply if a legal rental case is later established",
        "1981 construction requires drainage, wet-room, electrical, roof and alteration diligence; commute friction is material"
      ],
      take: "A credible space/value alternative rather than a location pick: four bedrooms, two stues, two baths, garden and gym-capable volume at 8.07m total. Treat the former rental section as family space only until municipal approvals, separation and market rent are documented."
    },
    {
      id: "fjordgata-10c",
      name: "Fjordgata 10C",
      area: "Varatun, Sandnes",
      type: "Enebolig",
      ask: 4.99,
      total: 5.116,
      sqm: 164,
      plot: 473,
      beds: 4,
      year: 1988,
      status: "live",
      viewing: "17 Sep · 16:15–17:15",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475795008",
      image: "https://images.finncdn.no/dynamic/default/2026/9/vertical-2/07/8/475/795/008_3a8daadf-fee0-410b-b0cc-fce76237475b.jpg",
      verdict: "watch",
      flags: ["family", "baths", "garden", "zones", "gym", "value", "forus", "risk"],
      scores: { family: 90, garden: 70, area: 62, risk: 30, forus: 92 },
      score: 65,
      facts: [
        "FINN verifies 4 bedrooms, 164 m² BRA-i, 473 m² owned plot, 1988 build and 5.12m total",
        "The area schedule verifies a loft living room and three bathrooms; the ad describes a screened garden, mark terrace and 73 m² double garage with loft",
        "The large garage makes rack plus treadmill credible without deleting a bedroom or second living zone, subject to dimensions, floor and temperature (inference)",
        "Varatun-to-Forus is roughly 10–18 minutes in ordinary traffic; E39 congestion can add friction (inference)"
      ],
      risks: [
        "The condition material says all three bathrooms and the laundry need major upgrading or total renovation; budget before treating the low price as savings",
        "The glazed balcony was not applied for, and the complete municipal/alteration file needs review",
        "No separate approved rental unit is advertised; no rental flag, rent or allowance assumed"
      ],
      take: "New value watch at 5.12m total: four bedrooms, two living zones, three baths, private garden and an unusually useful double garage close to Forus. The catch is structural rather than poetic—three old wet rooms, laundry and permit issues can consume a heroic fraction of the price gap."
    },
    {
      id: "bruvikveien-48c",
      name: "Bruvikveien 48C",
      area: "Mariero, Stavanger",
      type: "Enebolig",
      ask: 10.9,
      total: 11.174,
      sqm: 157,
      plot: 465,
      beds: 4,
      year: 2022,
      status: "sold",
      viewing: "Sold · confirmed 11 Sep; final price not visible",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=474768680",
      image: "https://images.finncdn.no/dynamic/1280w/2026/8/vertical-2/28/0/474/768/680_e27cfecd-99d4-4228-a699-c141447dad35.jpg",
      verdict: "sold",
      flags: ["family", "garden", "zones", "forus", "low-maintenance"],
      scores: { family: 82, garden: 70, area: 78, risk: 82, forus: 100 },
      score: 72,
      facts: [
        "FINN verifies 4 bedrooms, 157 m² BRA-i, 465 m² owned plot and 2022 build",
        "Ad verifies a loft living room, screened sunny garden, garage and EV charger",
        "Modern shell lowers near-term maintenance risk relative to the 1960s candidates (inference)",
        "Ordinary Forus drive is roughly 8–15 minutes (inference)"
      ],
      risks: [
        "At 157 m² with exactly four bedrooms, rack plus treadmill may consume garage utility or weaken the second living zone",
        "No rental unit is advertised; no rental allowance assumed",
        "Confirm there are at least two full bathrooms rather than one bathroom plus WC"
      ],
      take: "Sold status confirmed 11 Sep; achieved price is not visible. Retain briefly as the 11.17m advertised low-maintenance Mariero comp. Four bedrooms, loftstue and private garden were strong, but the bathroom count and garage-gym fit remained unresolved."
    },
    {
      id: "folkvordveien-101",
      name: "Folkvordveien 101",
      area: "Stangeland, Sandnes",
      type: "Enebolig",
      ask: 10.79,
      total: 11.061,
      sqm: 196,
      plot: 359,
      beds: 4,
      year: 2023,
      status: "live",
      viewing: "16 Sep · 17:00–17:45",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=471854980",
      image: "https://images.finncdn.no/dynamic/1280w/2026/8/vertical-2/07/0/471/854/980_36948dc2-901f-4e08-9dd8-d57e12d2f530.jpg",
      verdict: "watch",
      flags: ["family", "baths", "garden", "zones", "gym", "forus", "low-maintenance"],
      scores: { family: 90, garden: 58, area: 62, risk: 92, forus: 100 },
      score: 73,
      facts: [
        "FINN verifies 4 bedrooms, 196 m² BRA-i, 359 m² owned plot and 2023 build",
        "The ad explicitly verifies 2 living rooms, 2 bathrooms, laundry, finished outdoor zones and a spacious garage",
        "The garage is the credible rack-and-treadmill solution without sacrificing the four bedrooms or second living room (inference)",
        "Stangeland to Forus is roughly 5–12 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "The 359 m² plot is compact; verify how much level private lawn remains after house, garage and 63 m² of terraces",
        "Exactly four bedrooms means no spare-room buffer",
        "No rental unit is advertised; the owner-only ceiling therefore applies"
      ],
      take: "The low-maintenance new-build answer: every indoor requirement is explicitly present and Forus is easy. The unresolved question is whether the compact plot contains enough actual child lawn, rather than several elegant surfaces performing an impression of a garden."
    },
    {
      id: "somakroken-33",
      name: "Somakroken 33",
      area: "Stangeland, Sandnes",
      type: "Enebolig",
      ask: 10.9,
      total: 11.174,
      sqm: 331,
      plot: 807,
      beds: 6,
      year: 1951,
      status: "sold",
      viewing: "Sold · final price not visible",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=474512640",
      image: "https://images.finncdn.no/dynamic/default/2026/8/vertical-2/26/0/474/512/640_3c3a256e-866b-49a3-8339-ca13d53499cb.jpg",
      verdict: "sold",
      flags: ["family", "baths", "garden", "zones", "gym", "forus", "risk"],
      scores: { family: 96, garden: 85, area: 60, risk: 35, forus: 100 },
      score: 72,
      facts: [
        "FINN verifies 6 bedrooms, 331 m² BRA-i, 807 m² owned plot and 1951 build",
        "Three floors, several kitchens/living zones, multiple bathrooms and a 36 m² external store make family zoning and a dedicated gym physically easy",
        "The home was substantially modernised in 2021–2023 and has a large landscaped outdoor area",
        "Stangeland has a very practical Forus run, roughly 5–12 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "The ad explicitly says the separate section currently rented out is not approved for permanent residence or rental; no rental flag or income assumed",
        "Other rooms and alterations refer readers to the completion-certificate section, so approvals require line-by-line municipal verification",
        "The 1951 shell and unusually complex current use raise condition, fire-separation, insurance and remediation risk"
      ],
      take: "Sold. Retain briefly as a Forus-adjacent volume comp at 11.17m advertised total. The achieved price is not published, and the separate rented section was explicitly unapproved; its rent case therefore remains zero rather than becoming legal through the administrative miracle of a completed sale."
    },
    {
      id: "lyngholen-84",
      name: "Lyngholen 84",
      area: "Bogafjell, Sandnes",
      type: "Enebolig",
      ask: 9.39,
      total: 9.626,
      sqm: 207,
      plot: 407,
      beds: 4,
      year: 2003,
      status: "live",
      viewing: "14 Sep · 16:30–17:15",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=474664081",
      image: "https://images.finncdn.no/dynamic/default/2026/8/vertical-2/26/1/474/664/081_eb315328-8117-419a-a30e-bf9aadd0091a.jpg",
      verdict: "watch",
      flags: ["baths", "garden", "zones", "gym", "rental", "forus"],
      rentMonthly: 11000,
      scores: { family: 75, garden: 60, area: 45, risk: 75, forus: 90 },
      score: 67,
      facts: [
        "FINN verifies 4 bedrooms, 207 m² BRA-i, 407 m² owned plot and 2003 build",
        "The ad explicitly states a godkjent utleiedel earning NOK 11,000 per month",
        "Main house has living room plus loft living room and two bathrooms; a separate 38 m² garage gives credible gym capacity",
        "Bogafjell-to-Forus is roughly 10–20 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "The fourth bedroom belongs to the rental unit: keeping NOK 11,000/month leaves only three owner bedrooms, below the family brief",
        "Advertised rent is below the NOK 15,000 target and must be tested against the lease, inclusions and current market",
        "Vacancy, tenant wear, maintenance, tax/legal compliance and loss of family space reduce the headline income value"
      ],
      take: "Verified rental, awkward family arithmetic. NOK 11k/month is real advertised income rather than wishful yield, but the main house has only three bedrooms while the unit is occupied. Good reconnaissance for rental economics; not a complete six-person-family fit unless space is reclaimed or legally reconfigured."
    },
    {
      id: "gustav-vigelands-19",
      name: "Gustav Vigelands gate 19",
      area: "Trones, Sandnes",
      type: "Enebolig",
      ask: 6.7,
      total: 6.877,
      sqm: 165,
      plot: 555,
      beds: 6,
      year: 1972,
      status: "live",
      viewing: "14 Sep · 17:00–17:45",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475201411",
      image: "https://images.finncdn.no/dynamic/1280w/2026/8/vertical-2/31/1/475/201/411_3cef885d-548a-4bd4-a74a-889f2410aa14.jpg",
      verdict: "watch",
      flags: ["family", "baths", "garden", "zones", "value", "forus"],
      scores: { family: 88, garden: 72, area: 65, risk: 65, forus: 92 },
      score: 70,
      facts: [
        "FINN verifies 6 bedrooms, 165 m² BRA-i, 555 m² owned plot and 1972 build",
        "The ad states 5 bedrooms plus a TV-room/bedroom, 2 bathrooms, sunny terrace and child-usable garden",
        "The house was extensively renovated in 2017, including electrical, plumbing and windows according to the ad",
        "Trones to Forus is roughly 8–15 minutes in ordinary traffic (inference)"
      ],
      risks: [
        "Using the sixth room as a gym would consume the advertised TV room and weaken the two-zone brief; no separate rack-and-treadmill space is verified",
        "At 165 m², six sleeping rooms may make circulation, storage and shared spaces tighter than the bedroom count suggests",
        "Verify approvals and condition behind the 2017 renovation; no rental unit is advertised"
      ],
      take: "A compelling 6.88m value check, not a complete gym answer. Five bedrooms can remain while the TV room becomes training space, but that trades away the second proper living zone—the floor plan has performed the traditional miracle of counting one room twice."
    },
    {
      id: "boygen-15",
      name: "Bøygen 15",
      area: "Ullandhaugskråningen, Stavanger",
      type: "Tomannsbolig",
      ask: 6.55,
      total: 6.715,
      sqm: 148,
      plot: 280,
      beds: 5,
      year: 1961,
      status: "sold",
      viewing: "Sold · confirmed 11 Sep; final price not visible",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475467795",
      image: "https://images.finncdn.no/dynamic/1280w/2026/9/vertical-2/03/5/475/467/795_316156af-8525-41a6-9e26-3d8777f10c5e.jpg",
      verdict: "sold",
      flags: ["family", "baths", "garden", "zones", "value", "forus"],
      scores: { family: 78, garden: 55, area: 88, risk: 60, forus: 100 },
      score: 65,
      facts: [
        "FINN key information says 5 bedrooms, 148 m² BRA-i, 280 m² owned plot and 1961 build",
        "The body text instead says 4 bedrooms and 2 living rooms; it also verifies 2 bathrooms, a lawn garden and garage",
        "Ullandhaug gives an easy Forus run of roughly 7–15 minutes and immediate access to Sykkelstamveien (inference)"
      ],
      risks: [
        "Bedroom count conflicts within the live ad: treat four as the conservative number until the approved plan explains the fifth",
        "No dedicated gym volume is established; using the garage may sacrifice parking and still needs clear-height and floor checks",
        "The 280 m² plot and 148 m² interior are tight for the eventual six-person brief; no rental unit is advertised"
      ],
      take: "Sold status confirmed 11 Sep; achieved price is not visible. Retain briefly as the 6.71m advertised Ullandhaug duplex comp; its four-versus-five-bedroom contradiction, compact plot and unresolved garage-gym fit remain part of the comparison."
    },
    {
      id: "randeberggeilen-41",
      name: "Randeberggeilen 41",
      area: "Randaberg",
      type: "Enebolig",
      ask: 7.0,
      total: 7.176,
      sqm: 166,
      plot: 1327,
      beds: 4,
      year: 1960,
      status: "sold",
      viewing: "Sold 8 Sep · final price not visible",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=475199038",
      image: "https://images.finncdn.no/dynamic/1280w/2026/8/vertical-2/31/8/475/199/038_2a64fb5b-0402-4d0f-9d48-96e341f7064d.jpg",
      verdict: "sold",
      flags: ["family", "baths", "garden", "zones", "gym", "value", "risk"],
      scores: { family: 82, garden: 100, area: 55, risk: 20, forus: 45 },
      score: 64,
      facts: [
        "Broker verifies 4 bedrooms, 2 bathrooms, 2 living rooms, 166 m² BRA-i and a 1,327 m² owned plot",
        "Park-like private garden, greenhouse, pergola and double garage are exceptional at this price",
        "Kjeller rooms and garage provide credible gym space if moisture and approvals survive diligence (inference)",
        "Ordinary Forus drive is roughly 25–35 minutes and can worsen around E39 traffic (inference)"
      ],
      risks: [
        "Broker states the kjeller stue/kitchen and bathroom used as a hybel are not approved for that use; no rental flag or income assumed",
        "LNFR designation may restrict rebuilding, extensions and use changes",
        "Property is within a mapped landslide/possible quick-clay caution zone requiring geotechnical documentation for measures",
        "Modernisation need, planning deviations and defective garage doors make the low asking price less innocent than it first appears"
      ],
      take: "Sold on 8 Sep; achieved price is not visible. Retain briefly as the 7.18m advertised comp for exceptional land with exceptional footnotes: unapproved hybel, LNFR constraints, geotechnical caution and modernisation risk."
    },
    {
      id: "rosestien-1",
      name: "Rosestien 1",
      area: "Stokka, Stavanger",
      type: "Enebolig",
      ask: 12.5,
      total: 12.814,
      sqm: 297,
      plot: 892,
      beds: 5,
      year: 1971,
      status: "sold",
      viewing: "Sold · final price not visible",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=474154858",
      image: "https://images.finncdn.no/dynamic/1280w/2026/8/vertical-2/29/8/474/154/858_d044678b-6683-4c94-b993-0f00815cac24.jpg",
      verdict: "sold",
      flags: ["family", "baths", "garden", "zones", "gym", "rental", "benchmark"],
      scores: { family: 100, garden: 82, area: 95, risk: 82, forus: 82 },
      score: 87,
      facts: [
        "Broker and FINN material verify a sold 1971 house with 5 bedrooms, 3 living rooms, 3 bathrooms, 297 m² BRA-i and an 892 m² owned plot",
        "The ad explicitly describes the basement apartment as godkjent; advertised or achieved rent is not stated and must be verified",
        "The large basement and garage provide credible gym capacity, although the apartment competes for the easiest separated lower-floor space (inference)",
        "Stokka-to-Forus is roughly 14–20 minutes in ordinary traffic, with E39 peak variability (inference)"
      ],
      risks: [
        "The broker confirms the sale but neither achieved price nor rental income is published; 12.5m is only the last ask",
        "Do not underwrite the +2m rental allowance until unit separation, approval documents and market rent near 15k are evidenced",
        "Vacancy, tenant wear, maintenance, tax treatment and loss of family/gym space remain real costs"
      ],
      take: "Sold, but unusually useful: this is the preferred-area benchmark for five bedrooms, three living zones, three baths, real garden, gym flexibility and an approved unit at a 12.81m advertised total. Rent and achieved sale price remain unverified, because listings retain some modesty where numbers would be useful."
    },
    {
      id: "per-spelemanns-29",
      name: "Per Spelemanns vei 29",
      area: "Ullandhaug, Stavanger",
      type: "Enebolig",
      ask: 10.9,
      total: 11.174,
      sqm: 217,
      plot: 721,
      beds: 4,
      year: 1960,
      status: "sold",
      viewing: "Sold · final price not visible",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=472523998",
      image: "https://images.finncdn.no/dynamic/1280w/2026/8/vertical-2/08/8/472/523/998_72ccd71c-7671-4e36-957c-a70ef3f6def3.jpg",
      verdict: "sold",
      flags: ["family", "baths", "garden", "zones", "gym", "forus"],
      scores: { family: 90, garden: 90, area: 92, risk: 70, forus: 100 },
      score: 79,
      facts: [
        "FINN still marks the ad sold on 6 Sep 2026; final transaction price is not yet verified",
        "FINN verifies 4 bedrooms, 217 m² BRA-i, 721 m² owned plot and 1960 build",
        "Ad describes a mature private garden facing open recreational land, with greenhouse and several outdoor zones",
        "Multiple living areas and the lower-floor footprint make rack plus treadmill credible without deleting a bedroom (inference)",
        "Ordinary drive to Forus is roughly 8–15 minutes; local queues still matter (inference)"
      ],
      risks: [
        "No rental unit is advertised; no rental allowance assumed",
        "1960 shell plus extensions/alterations require a full permits, wet-room, drainage and electrical review",
        "At the upper owner-only range, renovation surprises would be particularly bureaucratic and expensive"
      ],
      take: "Sold. Retain briefly as the best recent Ullandhaug functional comp: 217 m², four bedrooms and a 721 m² garden at 11.17m advertised total. Asking is not the achieved sale price."
    },
    {
      id: "rognestien-8",
      name: "Rognestien 8",
      area: "Skadberg, Sola",
      type: "Enebolig",
      ask: 10.9,
      total: 11.174,
      sqm: 296,
      plot: 412,
      beds: 5,
      year: 2008,
      status: "sold",
      viewing: "Sold · final price not visible",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=474101266",
      image: "https://images.finncdn.no/dynamic/1280w/2026/8/vertical-2/22/6/474/101/266_21268005-0123-441d-9787-d4889e8ae304.jpg",
      verdict: "sold",
      flags: ["family", "baths", "garden", "gym", "forus"],
      scores: { family: 95, garden: 65, area: 72, risk: 78, forus: 95 },
      score: 75,
      facts: [
        "FINN still marks the ad sold on 6 Sep 2026; final transaction price is not yet verified",
        "FINN verifies 5 bedrooms, 2 bathrooms, 296 m² BRA-i, 412 m² owned plot and 2008 build",
        "Ad describes three floors, a hagestue, two large terraces and the possibility of a sixth bedroom",
        "Triple garage plus two large storage rooms make a dedicated rack-and-treadmill zone credible without deleting family space (inference)",
        "Ordinary drive to Forus is roughly 8–15 minutes, with Sola/Forus peak traffic variability (inference)"
      ],
      risks: [
        "No rental unit is advertised; no rental allowance assumed",
        "The 412 m² plot is compact relative to the 296 m² house, so verify how much level, private child-usable lawn remains beyond terraces and hagestue",
        "Confirm the floor plan provides two proper indoor living zones; the headline and summary do not document them clearly"
      ],
      take: "Sold. This remains a useful Skadberg comp for modern family volume and gym capacity at 11.17m advertised total; asking is not the achieved sale price."
    },
    {
      id: "teineveien-28",
      name: "Teineveien 28",
      area: "Hommersåk, Sandnes",
      type: "Enebolig",
      ask: 6.99,
      total: 7.166,
      sqm: 294,
      plot: 689,
      beds: 5,
      year: 1983,
      status: "sold",
      viewing: "Sold · final price not visible",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=474571071",
      image: "https://images.finncdn.no/dynamic/1280w/2026/8/vertical-2/26/1/474/571/071_f5f88ec0-3003-40c2-acec-d1cc7f5a2193.jpg",
      verdict: "sold",
      flags: ["family", "baths", "garden", "zones", "gym", "rental", "value"],
      scores: { family: 94, garden: 82, area: 50, risk: 62, forus: 55 },
      score: 76,
      facts: [
        "FINN still marks the ad sold on 6 Sep 2026; final transaction price is not yet verified",
        "FINN verifies 294 m² BRA-i, 5 bedrooms in the description, 3 bathrooms, 2 living rooms and a 689 m² owned plot",
        "The ad explicitly states a godkjent utleiedel; advertised or achieved rent is not stated and must be verified",
        "Three floors, integrated garage and 334 m² total BRA leave credible dedicated gym volume (inference)",
        "Ordinary Forus drive is roughly 25–35 minutes and vulnerable to Rv13/Hove traffic (inference)"
      ],
      risks: [
        "Do not underwrite 15k/month until unit size, separation, demand and documentary approval are checked",
        "Vacancy, tenant wear, maintenance, tax treatment and the family-space sacrificed to the unit remain real costs",
        "Hommersåk commute friction is the price of the unusually strong space economics"
      ],
      take: "Sold. Retain briefly as the value/rental comp: 7.17m advertised total bought unusual space plus a verified approved unit, though achieved price and rent remain unverified."
    },
    {
      id: "myrvegen-20",
      name: "Myrvegen 20",
      area: "Tananger, Sola",
      type: "Enebolig",
      ask: 7.5,
      total: 7.689,
      sqm: 242,
      plot: 1206,
      beds: 7,
      year: 1968,
      status: "sold",
      viewing: "Sold · final price not visible",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=473834353",
      image: "https://images.finncdn.no/dynamic/1280w/2026/8/vertical-2/22/3/473/834/353_51f6c87d-c482-419f-b2ae-e57228a8815f.jpg",
      verdict: "sold",
      flags: ["family", "baths", "garden", "zones", "gym", "value"],
      scores: { family: 95, garden: 98, area: 65, risk: 55, forus: 78 },
      score: 76,
      facts: [
        "FINN still marks the ad sold on 6 Sep 2026; final transaction price is not yet verified",
        "FINN verifies 7 bedrooms, 242 m² BRA-i, 293 m² total BRA and a 1,206 m² owned plot",
        "The ad describes several living rooms and a large garage; family zoning and a dedicated gym are credible (inference)",
        "Large private plot is unusually strong for children and future optionality",
        "Ordinary Forus drive is roughly 15–25 minutes, with Tananger/Sømmevågen traffic variability (inference)"
      ],
      risks: [
        "1968 construction and the low price per square metre demand serious condition, drainage, roof, wet-room and electrical diligence",
        "Seven advertised bedrooms do not by themselves prove every room is legally approved for permanent residence",
        "No legal rental unit is advertised; do not infer one from spare rooms or floor separation"
      ],
      take: "Sold comp: enormous family capacity and child-usable land was offered at 7.69m total, with a practical rather than perfect Forus run. Asking is not achieved price; retain briefly while the sale figure catches up with reality."
    },
    {
      id: "syrin",
      name: "Syrinveien 11",
      area: "Eiganes, Stavanger",
      type: "Enebolig",
      ask: 13.2,
      total: 13.54,
      sqm: 242,
      plot: 1016,
      beds: 5,
      year: 1936,
      status: "sold",
      viewing: "Permanent sold benchmark",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=377615749",
      image: "https://images.finncdn.no/dynamic/1280w/2024/10/vertical-2/14/9/377/615/749_4dc2a74d-e1d3-480e-992e-c00fa475185b.jpg",
      verdict: "sold",
      flags: ["family", "baths", "garden", "zones", "gym", "benchmark"],
      scores: { family: 96, garden: 94, area: 95, risk: 78, forus: 92 },
      score: 83,
      facts: [
        "Permanent benchmark retained by instruction",
        "Five-bedroom Eiganes family-house reference with large plot and strong zoning"
      ],
      risks: ["Historic listing is no longer live; figures are benchmark data, not a current offer"],
      take: "The permanent sold benchmark: close to the functional ideal, useful for judging what the preferred-area premium buys."
    }
  ]
};
