window.WAR_ROOM = {
  scrapedAt: "2026-08-20T18:04:00+02:00",
  scrapedLabel: "20 Aug 2026, 18:04 CEST",
  stats: {
    eiganesHouses: 17,
    valandHouses: 4,
    fitCount: 1,
    yoy: "11.1%",
    sqm: "~58k"
  },
  houses: [
    {
      id: "hoigard",
      name: "Lektor Einar Høigårds gate 1",
      area: "Eiganes vest / Lassa",
      type: "Enebolig",
      ask: 11.99, total: 12.29, sqm: 318, plot: 487, beds: 3, year: 1978,
      status: "live", verdict: "strong",
      viewing: "By appointment",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=462844743",
      flags: ["zones", "gym", "garden", "garage"],
      scores: { family: 80, garden: 72, area: 90, risk: 70, forus: 82 },
      take: "Still the only live house that actually resembles the brief. 318 m² BRA-i / 338 m² total, 487 m² owned plot, terraces, double garage, extra kitchen downstairs, upgraded baths and enough volume for rack+treadmill plus adult/kid zones. Official count is still 3 bedrooms / 4 rooms, so the fourth bed remains a floorplan/legal question. Above the 11m reference, but not stupid. Recon only."
    },
    {
      id: "bokfink",
      name: "Bokfinkveien 26",
      area: "Sandal",
      type: "Enebolig · 1954",
      ask: 9.5, total: 9.74, sqm: 160, plot: 1073, beds: 3, year: 1954,
      status: "live", verdict: "watch",
      viewing: "Wed 26 Aug 16:00–17:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=473900649",
      flags: ["garden", "garage", "zones"],
      scores: { family: 56, garden: 94, area: 76, risk: 34, forus: 80 },
      take: "New today-ish: 1 073 m² owned plot at the end of a Sandal blindvei, Stokkavatnet as the neighbour, 9.5m ask. That land is compound-shaped. The house is not: 160 m² BRA-i / 177 m², 3 beds / 4 rooms, 1954, 'modernisering må påregnes', garage only 17 m². Basement 51 m² could become gym later if you survive the archaeology. Watch the plot, don’t fall in love with the building."
    },
    {
      id: "vestbo",
      name: "Vestbøtunet 41A / 41B",
      area: "Stokka",
      type: "Enebolig · hybel/sokkel · two units",
      ask: 10.5, total: 10.76, sqm: 190, plot: 540, beds: 4, year: 1985,
      status: "live", verdict: "watch",
      viewing: "Mon 24 Aug 16:00–17:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=472851006",
      flags: ["beds", "garden", "zones", "rental"],
      scores: { family: 74, garden: 76, area: 91, risk: 62, forus: 82 },
      take: "Ukens bolig, same 10.5m ask. 540 m² owned plot, 190 m² BRA-i, 4 bedrooms, child-friendly tags, 42 m² terrace and a secondary unit upgraded in 2022. Still a registered enebolig with hybel/sokkelleilighet, two boenheter, plus rammetillatelse for extension/facade/new garage/extra driveway. Could become a compound; today it is a project wearing a nice jacket."
    },
    {
      id: "hornklove",
      name: "Torbjørn Hornkloves gate 37",
      area: "Våland",
      type: "Enebolig · 1915",
      ask: 11.99, total: 12.29, sqm: 261, plot: 396, beds: 3, year: 1915,
      status: "live", verdict: "watch",
      viewing: "Sun 23 Aug 16:00–17:00",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=473171110",
      flags: ["zones", "baths", "gym"],
      scores: { family: 69, garden: 58, area: 84, risk: 42, forus: 80 },
      take: "Still live, still pretty: 261 m², 396 m² corner plot, two stuer, loftstue, basement with own entrance, vaskerom, kjellerstue and a disponible room. Two baths upstairs plus guest WC is good; 1915 + energy F is the maintenance gods asking for tribute. Same ask as Høigårds for less garden and more archaeology. Watch, don’t worship."
    },
    {
      id: "madlavei-6c",
      name: "Gamle Madlaveien 6C",
      area: "Eiganes",
      type: "Enebolig · new byvilla 2026",
      ask: 14.85, total: 14.92, sqm: 196, plot: null, beds: 3, year: 2026,
      status: "live", verdict: "dream",
      viewing: "By appointment / signup only",
      url: "https://www.finn.no/realestate/projectsingle/ad.html?finnkode=423023110",
      flags: ["zones", "newer", "premium"],
      scores: { family: 68, garden: 42, area: 90, risk: 80, forus: 84 },
      take: "New on the board: Eiganesveien 168 byvilla, 196 m², 3 (maybe 4) beds, two stuer, ungdomsavdeling in the basement, carport, handover Q3 2026. Functionally closer than the 25m Swiss sibling. Garden is a shared green between houses, not a private kid-chaos plot. 14.85m for 196 m² is still boutique-hotel money. Dream/price ceiling, not a 2027 target."
    },
    {
      id: "madlavei-10",
      name: "Gamle Madlavei 10",
      area: "Eiganes",
      type: "Enebolig · new Swiss villa 2026",
      ask: 25.0, total: 25.63, sqm: 211, plot: 930, beds: 4, year: 2026,
      status: "live", verdict: "dream",
      viewing: "By appointment / signup only",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=454755791",
      flags: ["beds", "garden", "garage", "premium"],
      scores: { family: 76, garden: 94, area: 90, risk: 74, forus: 84 },
      take: "Rebuilt Swiss villa, 211 m², 4 beds, garage tag and a genuine 930 m² Eiganes plot. Garden math is unicorn. Price math is a different religion. 25m for 211 m² is compound-adjacent land with boutique-hotel invoices. Keep as a plot/area ceiling, not a 2027 target."
    },
    {
      id: "jens-tvedts",
      name: "Jens Tvedts gate 4",
      area: "Kampen",
      type: "Tomannsbolig",
      ask: 4.99, total: 5.12, sqm: 116, plot: null, beds: 4, year: null,
      status: "live", verdict: "wrong",
      viewing: "Thu 20 Aug 17:30",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=468697314",
      flags: ["cheap", "beds"],
      scores: { family: 42, garden: 30, area: 64, risk: 66, forus: 78 },
      take: "Still in the Eiganes/Stokka/Sandal search bucket, still Kampen, still only 116 m². Four bedrooms at 5m is cute, like a golden retriever in a spreadsheet, but this is not a compound: no convincing garden, no gym path, no 2-zone family HQ. Useful only as market noise."
    },
    {
      id: "steingata",
      name: "Steingata 41",
      area: "Eiganes",
      type: "Hel tomannsbolig",
      ask: 9.75, total: 10.0, sqm: 166, plot: null, beds: 4, year: null,
      status: "live", verdict: "watch",
      viewing: "By appointment",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=465832042",
      flags: ["beds", "rental", "garage"],
      scores: { family: 64, garden: 48, area: 88, risk: 66, forus: 84 },
      take: "Still live. Whole two-family house with garage/parking, 2025 roof and 17k/month rental income. That income is real; so is the compromise. 166 m² is tight for compound mode, and making a gym probably means cannibalising the rental unit. Useful Eiganes foothold, weak family HQ."
    },
    {
      id: "bretland-28",
      name: "Bretlandsgata 28",
      area: "Eiganes",
      type: "Tomannsbolig · townhouse",
      ask: 15.9, total: 16.3, sqm: 179, plot: null, beds: 3, year: null,
      status: "live", verdict: "dream",
      viewing: "Tue 25 Aug 16:30",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=471177161",
      flags: ["baths", "zones", "premium"],
      scores: { family: 60, garden: 38, area: 92, risk: 78, forus: 84 },
      take: "Premium Eiganes townhouse: 3 beds, 3 baths, 4 stuer and designer-kitchen nonsense. Lovely object, bad compound math. At 15.9m for 179 m², the price per square meter has climbed Corporate Olympus and started billing consulting hours. Keep as dream/price ceiling, not a target."
    },
    {
      id: "bretland-30",
      name: "Bretlandsgata 30",
      area: "Eiganes",
      type: "Tomannsbolig · townhouse",
      ask: 15.9, total: 16.3, sqm: 175, plot: null, beds: 3, year: null,
      status: "live", verdict: "dream",
      viewing: "Tue 25 Aug 16:30",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=471179333",
      flags: ["premium", "newer"],
      scores: { family: 58, garden: 36, area: 92, risk: 80, forus: 84 },
      take: "Sibling to Bretlandsgata 28: new, polished, expensive, and too townhouse-shaped for Alex’s must-haves. It probably photographs like a boutique hotel. It also asks compound money without compound outdoor space. Nice market reference, wrong target."
    },
    {
      id: "kampensgata",
      name: "Kampensgata 61",
      area: "Kampen",
      type: "Enebolig",
      ask: 9.7, total: 9.94, sqm: 220, plot: 382, beds: 3, year: 1937,
      status: "live", verdict: "wrong",
      viewing: "By appointment / signup only",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=468139013",
      flags: ["garage", "garden"],
      scores: { family: 60, garden: 58, area: 70, risk: 48, forus: 78 },
      take: "Still in the search bucket, still Kampen rather than the preferred belt. 220 m², 382 m² plot, garage and upgraded bits are useful. Three bedrooms, energy F and likely not 2-bath/family-compound simple. Under 10m is tempting bait; the brief says this is mostly the wrong animal."
    },
    {
      id: "welhavens",
      name: "Welhavens gate 1A/B",
      area: "Eiganes",
      type: "Enebolig · approved apartment",
      ask: 22.5, total: 23.08, sqm: 272, plot: null, beds: 6, year: 2011,
      status: "live", verdict: "dream",
      viewing: "By appointment",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=448368685",
      flags: ["beds", "rental", "premium"],
      scores: { family: 82, garden: 52, area: 90, risk: 76, forus: 84 },
      take: "Eiganes, 2011, 272 m², 6 bedrooms and approved apartment. Functionally interesting, financially in another solar system. At 22.5m ask it is a luxury comp, not a 2027 reconnaissance target unless someone discovers oil under the sofa."
    },
    {
      id: "misjonsveien",
      name: "Misjonsveien 52",
      area: "Kampen",
      type: "Del av tomannsbolig",
      ask: 4.49, total: 4.60, sqm: 87, plot: null, beds: 2, year: null,
      status: "live", verdict: "wrong",
      viewing: "Mon 24 Aug 16:15",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=471877789",
      flags: ["cheap"],
      scores: { family: 28, garden: 16, area: 62, risk: 68, forus: 78 },
      take: "Half a two-family house, 87 m², 2 bedrooms, loft, balcony, EV charger. Fine student/BI commute object. Zero compound. Ignore unless you are collecting Kampen postage stamps."
    },
    {
      id: "drgraesli",
      name: "Dr. Græslis vei 13C",
      area: "Vålandskråningen",
      type: "Rekkehus",
      ask: 5.49, total: 5.63, sqm: 133, plot: null, beds: 2, year: null,
      status: "live", verdict: "wrong",
      viewing: "Thu 20 Aug 16:30",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=473172605",
      flags: ["cheap"],
      scores: { family: 38, garden: 24, area: 76, risk: 70, forus: 80 },
      take: "Still the wrong little bastard. 133 m² rekkehus, 2 bedrooms, good standard and nice view perhaps, but no compound garden and no rack+treadmill path without evicting normal life. Fine for someone else."
    },
    {
      id: "furras",
      name: "Furras gate 15",
      area: "Våland",
      type: "Enebolig",
      ask: 6.95, total: 7.12, sqm: 201, plot: 161, beds: 5, year: 1910,
      status: "live", verdict: "trap",
      viewing: "By appointment",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=472396798",
      flags: ["beds", "zones"],
      scores: { family: 58, garden: 28, area: 82, risk: 32, forus: 80 },
      take: "Unchanged trap. Five bedrooms and a 1910 soul for 7m sounds clever until the 161 m² plot and 'modernisering kan påregnes' walk in wearing a plague mask. Rooms: yes. Kid outdoor chaos: no. Gym: cellar project after you spend the savings. Not the compound."
    },
    {
      id: "muse",
      name: "Muségata 55",
      area: "Våland",
      type: "Enebolig · 1911 sveitserjugend",
      ask: 10.29, total: 10.55, sqm: 173, plot: null, beds: 3, year: 1911,
      status: "live", verdict: "wrong",
      viewing: "By appointment",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=463370141",
      flags: ["garden", "heritage"],
      scores: { family: 48, garden: 55, area: 84, risk: 40, forus: 78 },
      take: "Still listed. Prize-winning heritage villa, garden, garage, charm by the bucket. Also 173 m², three bedrooms and conservation/old-house constraints. Beautiful problem, wrong operating base."
    },
    {
      id: "spurve",
      name: "Spurvekroken 6",
      area: "Sandal",
      type: "Enebolig",
      ask: 8.5, total: 8.71, sqm: 240, plot: 330, beds: 3, year: 1983,
      status: "sold", verdict: "sold",
      viewing: "Sold / still marked Solgt on FINN",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=469178413",
      flags: ["zones", "gym", "garage"],
      scores: { family: 70, garden: 62, area: 74, risk: 58, forus: 80 },
      take: "Still marked sold. Keep as the cheap Sandal comp: 240 m², 330 m² plot, garage, two kitchens/zones and a 1983 soul near Stokkavannet. Officially 3 bedrooms, unofficially more if you ignore the legal banana peel. This is what ~8.5m just bought when someone accepted the approval risk."
    },
    {
      id: "rogaland",
      name: "Rogalandsgata 19",
      area: "Våland",
      type: "Enebolig · 1917",
      ask: 15.0, total: 15.38, sqm: 347, plot: 902, beds: 6, year: 1917,
      status: "sold", verdict: "sold",
      viewing: "Sold / gone from the live Våland search",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=470177249",
      flags: ["beds", "garden", "zones", "gym", "rental", "garage"],
      scores: { family: 94, garden: 96, area: 86, risk: 62, forus: 80 },
      take: "Off the live search now. Keep as the dream-comp: 347 m² BRA-i / 381 m² total, 902 m² owned plot, 6 beds, 3 baths by floor description, double garage, basement rental setup and several living zones. It was the actual compound if budget stopped mattering; now it teaches what 15m Våland unicorns look like when they vanish."
    },
    {
      id: "stokkavei",
      name: "Øvre Stokkavei 82A",
      area: "Stokka",
      type: "Enebolig",
      ask: 10.5, total: 10.76, sqm: 163, plot: null, beds: 4, year: null,
      status: "sold", verdict: "sold",
      viewing: "Sold",
      url: "https://www.finn.no/realestate/homes/ad.html?finnkode=472024319",
      flags: ["beds", "gym", "rental"],
      scores: { family: 76, garden: 55, area: 88, risk: 78, forus: 82 },
      take: "Still absent from the live search, so keep it as a fresh sold comp for now. Upgraded 2023–24, four bedrooms, hybel around 11k/month. This is what ~10.5m recently bought on Stokka when someone else had already done the expensive wet-room suffering."
    },
    {
      id: "syrin",
      name: "Syrinveien 27 · benchmark",
      area: "Stokka",
      type: "Enebolig · ghost",
      ask: 12.5, total: 12.5, sqm: 300, plot: 700, beds: 3, year: 1978,
      status: "sold", verdict: "sold",
      viewing: "Sold June 2026 · tinglyst 8 Jun · public range 10–15m",
      url: "https://www.hjemla.no/norge/stavanger/4022-stavanger/syrinveien-27",
      flags: ["garden", "zones", "gym"],
      scores: { family: 88, garden: 90, area: 92, risk: 60, forus: 80 },
      take: "Permanent sold benchmark. Big Stokka house, big plot, enough internal weirdness to make the plan matter more than the bedroom count. If a live listing does not beat this feeling, keep walking and let someone else pay retail for brochure adjectives."
    }
  ]
};
